version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save ""

volumes:
  gem_cache:
  redis_data:
